version: "3.9"

services:
  
  jenkins:
     container_name: "jenkins-container"
     image: "jenkins/jenkins:lts"
     ports: 
       - '80:8080'
       - '50000:50000'

  sonarqube:
    container_name: "sonarqube-container"        
    image: "sonarqube:8.9.3-community"
    volumes:
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
    expose:
      - "9000"
    ports:
      - '9000:9000'

  